services:
  - type: web
    name: image-pdf-converter
    env: python
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y poppler-utils"
    startCommand: "gunicorn app:app"